USE WAREHOUSE COMPUTE_WH;
SELECT CURRENT_WAREHOUSE();

CREATE DATABASE OLIST_DB;
SHOW DATABASES;
USE DATABASE OLIST_DB;

CREATE SCHEMA RAW;
SHOW SCHEMAS;

CREATE STAGE OLIST_STAGE;
SHOW STAGES;
LIST @OLIST_STAGE;

CREATE FILE FORMAT OLIST_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

SHOW FILE FORMATS;