USE WAREHOUSE COMPUTE_WH;
USE DATABASE OLIST_DB;
USE SCHEMA RAW;

COPY INTO CUSTOMERS
FROM @OLIST_STAGE/olist_customers_dataset.csv
FILE_FORMAT = (FORMAT_NAME = OLIST_CSV_FORMAT);

SELECT COUNT(*) FROM CUSTOMERS;


COPY INTO ORDERS
FROM @OLIST_STAGE/olist_orders_dataset.csv
FILE_FORMAT = (FORMAT_NAME = OLIST_CSV_FORMAT);

COPY INTO ORDER_ITEMS
FROM @OLIST_STAGE/olist_order_items_dataset.csv
FILE_FORMAT = (FORMAT_NAME = OLIST_CSV_FORMAT);

COPY INTO ORDER_PAYMENTS
FROM @OLIST_STAGE/olist_order_payments_dataset.csv
FILE_FORMAT = (FORMAT_NAME = OLIST_CSV_FORMAT);

COPY INTO PRODUCTS
FROM @OLIST_STAGE/olist_products_dataset.csv
FILE_FORMAT = (FORMAT_NAME = OLIST_CSV_FORMAT);

COPY INTO PRODUCT_CATEGORY_TRANSLATION
FROM @OLIST_STAGE/product_category_name_translation.csv
FILE_FORMAT = (FORMAT_NAME = OLIST_CSV_FORMAT);