USE WAREHOUSE COMPUTE_WH;
USE DATABASE OLIST_DB;
USE SCHEMA RAW;

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CUSTOMERS
UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS
UNION ALL
SELECT 'ORDER_PAYMENTS', COUNT(*) FROM ORDER_PAYMENTS
UNION ALL
SELECT 'PRODUCTS', COUNT(*) FROM PRODUCTS
UNION ALL
SELECT 'PRODUCT_CATEGORY_TRANSLATION', COUNT(*) FROM PRODUCT_CATEGORY_TRANSLATION;

-- Customers
SELECT * FROM CUSTOMERS
LIMIT 10;

-- Orders
SELECT * FROM ORDERS
LIMIT 10;

-- Order Items
SELECT * FROM ORDER_ITEMS
LIMIT 10;

-- Order Payments
SELECT * FROM ORDER_PAYMENTS
LIMIT 10;

-- Products
SELECT * FROM PRODUCTS
LIMIT 10;

-- Product Category Translation
SELECT * FROM PRODUCT_CATEGORY_TRANSLATION
LIMIT 10;