[project]
name = "snowflake-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-ollama>=1.1.0",
    "langchain-snowflake>=0.2.3",
    "langchain-text-splitters>=1.1.2",
    "pypdf>=6.18.0",
    "python-dotenv>=1.2.3",
    "snowflake-connector-python>=4.7.3",
    "snowflake-sqlalchemy>=1.11.1",
]
